### ISSUE TITLE
[Bug]: @web3-onboard/walletconnect eth_chainId always returns 0x1

### ISSUE THREAD

**Issue by danpetban** [blocknative/web3-onboard#890] opened 2022-03-21 16:21 UTC
### Current Behavior

If the requested method is `eth_chainId` the provider retrieves the chain id from the connector.
```
if (method === 'eth_chainId') {
  return `0x${this.connector.chainId.toString(16)}`
}
```

It defaults to `0x1`, because in the `connector` init, no chain option was passed.
```
const connector = new WalletConnect({
  bridge
})
```

According to this, it always defaults to the eth mainnet network and gives error when the `web3.eth.getGasPrice()` called.

### Expected Behavior

As the Walletconnect ethereum provider's documentation shows, we need to be able to pass the rpc options.
https://docs.walletconnect.com/2.0/quick-start/dapps/ethereum-provider

I see that you override the commonly used `@walletconnect/ethereum-provider` package, so I'm not sure if it is the best way to implement as mentioned in the docs. 

The goal is to be able to use another networks.

### Steps To Reproduce

Just follow the @web3-onboard/walletconnect docs.
https://docs.blocknative.com/onboard/wallet-connect

### Onboard Version

core: 2.0.11, walletconnect: 2.0.1

### Node Version

16

**Comment by band94** [comment] 2022-03-28 15:34
Did some research, and figured out if you pass the desired `chainId` to the `connector` when the `createSession` called, it's going to work.

I achieved this with the override of the walletconnect init. Passed another prop, called `currentChainId` and used like this:
```
this.connector.createSession({chainId: currentChainId})
```
The problem with this semi-solution is that the provider can't change the network dinamically.


To clarify the problem:
With the current core and walletconnect version, you can't use another network than eth mainnet.
In my case, I want to use Matic network, but when I want to sign a transaction the plugin throws the following error:
`The Provider does not have a rpcUrl to make a request for the requested method:  ${method}`.

@aaronbarnardsound Can you acknowledge if it is a bug or point out what am i missing please?

**Comment by aaronbarnardsound** [comment] 2022-03-29 01:49
Hey @band94 I am going to take a look at this and get back to you.

**Comment by aaronbarnardsound** [comment] 2022-03-29 02:57
@band94 I might be missing what you are saying, so let me know if that is the case. It is my understanding that the `chainId` is defined and controlled by the wallet that is being connected. So if I were to connect MetaMask mobile via WalletConnect, then whatever network I have my wallet set to is what WalletConnect will return via the `eth_chainId` method. You can test this out in our [React Demo](https://reactdemo.blocknative.com/) by connecting MetaMask mobile and then switching networks within the MM app and you will see the React app pickup the network change.

That error: `The Provider does not have a rpcUrl to make a request for the requested method: ${method}` occurs when you are making a RPC request with a method that we do not patch and we cannot find a rpcUrl that matches the wallet's current connected network within the chains array. We patch the sign and send transaction methods, so you must have been calling something else?
Was the wallet connected to / support the matic network?

**Comment by band94** [comment] 2022-03-29 08:43
I tried to use Trust Wallet with Walletconnect. It supports the Polygon network.
The difference between MM app and TW app is in TW app, you can't define a custom rpc network.

I'm not sure if the TW app returns `1` as chainId or it defaults in your plugin.
In my case the `getGasPrice` call throws the error, because it sees that the current chainId is `1` instead of `137`.

Also, I checked with the MM app and you are right, it works fine for me as well.

**Comment by aaronbarnardsound** [comment] 2022-03-30 00:04
Hmmm maybe there is a WalletConnect implementation issue on the Trust wallet side?

**Comment by aaronbarnardsound** [comment] 2022-04-06 06:08
Closing this for the moment as it seems that it is an Trust wallet implementation issue. Feel free to open if you find that it is a  problem on our end.

**Comment by band94** [comment] 2022-04-06 09:10
My only problem is that it worked fine with the previous onboard version (v1).

In the walletconnect [doc](https://docs.walletconnect.com/2.0/migration#multi-chain-support) you can see the wallet itself no longer controls the chainId, but the session does.  
As you mentioned before you expect the wallet to do this.

Maybe it has something to do with this?

**Comment by aaronbarnardsound** [comment] 2022-04-11 00:38
We are still on V1 of WalletConnect since we found that V2 was still super buggy when implementing. Could that have something to do with it? Does Trust support V1 in a backwards compatible way?
I will try and do some more digging on my end.

**Comment by aaronbarnardsound** [comment] 2022-06-09 03:44
Closing due to inactivity. Feel free to reopen if you are still having issues :)

**Closed by aaronbarnardsound** 2022-06-09 03:44 UTC
Labels: bug

**Comment by rbruels** [comment] 2022-08-06 17:14
@aaronbarnardsound et al — would like to reopen this one! Experiencing this with WalletConnect, Rainbow Wallet, `web3-onboard/core@2.6.0` and `@web3-onboard/walletconnect@2.0.8`. 

I have 100% set Rinkeby (0x4) as Rainbow's network (and it shows I am using Rinkeby in the Rainbow UX). I experienced the same error as @danpetban when signing a transaction:

```The Provider does not have a rpcUrl to make a request for the requested method: ${method}.```

Despite the error message (which sent me down a long, painful, and eventually irrelevant rabbit trail), if you look at `walletconnect/src/index.ts:223` you'll see why:

- Line 223: `eth_chainId` is always returning `0x1` despite being connected to Rinkeby
- Currently I am only init'ing Onboard with the Rinkeby/0x4 chain
- Line 225 checks if there's a provider for `0x1` (returned by `eth_chainId`), which there's not in my config
- Line 226 checks if that chain is provided anywhere in Onboard init (which it's not, in my config)
- Line 229 throws the not-exactly-accurate error about there not being an rpcUrl to support a method (when the problem is really that the chain returned by `eth_chainId` is not configured)

👆 So this info is really just to inform a change to make the error message more accurate, but the root problem is that `eth_chainId` is always returning `0x1` despite being configured on another chain.

**Comment by rbruels** [comment] 2022-08-06 17:36
If helpful:
- I've confirmed line 7 `getInterface: async ({ chains, EventEmitter }) => {` -- `chains` correctly specifies only my Rinkeby/0x4
- Line 93 `const { accounts, chainId } = this.connector.session;` -- `chainId` is coming back as `0x1` here

**Comment by rbruels** [comment] 2022-08-06 17:44
lol — and I just realized in Rainbow, despite the UX showing "Rinkeby" at the bottom, when sending a transaction, you still need to switch networks in the approval UX. Once I switched the network from Ethereum to Rinkeby in that modal, WalletConnect correctly sent back chain ID `0x4`.

So, I propose this bug just address the poor error message ... 🙂
