### ISSUE TITLE
[Bug]: Ledger always locked

### ISSUE THREAD

**Issue by JLiebow** [blocknative/web3-onboard#1353] opened 2022-11-07 23:17 UTC
### Current Behavior
<img width="1757" alt="Screen Shot 2022-11-07 at 3 17 48 PM" src="https://user-images.githubusercontent.com/81650991/200435817-bee0ab96-fb91-44e9-ad32-603f6b68b266.png">

I am able to unlock and connect my ledger nano s plus to chromes hardware connection modal. However, after connecting I come to the above modal and am told that my ledger is locked and no accounts are detected. Please assist, I am not sure how to proceed without a clearer error. 

My ledger nanos S plus is always locked regardless of unlocking with pin.

### Expected Behavior

I would expect that unlocking my ledger with pin would allow me to select a valid account and access signing functionality from my ledger nano s plus.

### Steps To Reproduce

My app was built with create react app 5 and uses the below versions in package.json
"@web3-onboard/core": "^2.10.0",
"@web3-onboard/ledger": "2.3.1",

here is the relevant code.

const ledger = ledgerModule()
  
  const onboard = Onboard({
    // ... other Onboard options
    chains: [
        {
          id: '0x01',
          token: 'ETH',
          label: 'Ethereum Mainnet',
          rpcUrl:"some rpc url"
        }
      ],
    wallets: [
      ledger
    ]
  })
  
  const connectedWallets = await onboard.connectWallet()

### What package is effected by this issue?

@web3-onboard/core

### Is this a build or a runtime issue?

Runtime

### Package Version

2.10.0

### Node Version

16

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
logs are posted in "Anything else" and are generic. commenting out the ledger module import fixes the console errors.
```

### Anything else?

<img width="556" alt="Screen Shot 2022-11-07 at 3 13 38 PM" src="https://user-images.githubusercontent.com/81650991/200435280-ee30c891-9cf1-4fcb-a120-548c845a09b3.png">

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by taylorjdawson** [comment] 2022-11-08 19:39
Hey @JLiebow thanks for raising this issue, we'll see if we can repro and then asses what the issue is, thanks!

**Comment by JLiebow** [comment] 2022-11-14 19:18
swapping to react version fixed core issue but strange generic errors remain

**Comment by Adamj1232** [comment] 2022-11-18 17:41
@JLiebow glad it is working for you! What is the generic error you are seeing? Can you elaborate on swapping react versions?

**Comment by techgangboss** [comment] 2023-01-12 20:59
Hey @JLiebow we'll be closing this issue by end of week unless you want to followup on the generic errors

**Comment by ejc8** [comment] 2023-02-01 16:35
Closing this issue - feel free to reopen if needed

**Closed** 2023-02-01 16:35 UTC
Labels: bug
