### ISSUE TITLE
[Bug]: Invalid derivation path

### ISSUE THREAD

**Issue by ziogaschr** [blocknative/web3-onboard#1261] opened 2022-09-09 18:42 UTC
### Current Behavior

I am trying to connect Gnosis Safe with Ledger HD wallet using a custom derivation path for the Ethereum Classic chain (as well the Ethereum Classic Ledger App). When setting a custom derivation path `m/44'/61'/0'/0/0`, I receive the error `m/44'/61'/0'/0/0 is not a valid derivation path`.

This way I am not able to pick the account I want from Ledger.

![image](https://user-images.githubusercontent.com/802700/189421165-640e696a-0684-4426-879c-2d3d6e337e60.png)

I am sorry, if this is not the correct repo, but based on modal that is powered by Blocknative, I thought that this is a good candidate.

### Expected Behavior

To connect with Ledger, getting the correct address from the Ledger's **Ethereum Classic** app.

### What package is effected by this issue?

@web3-onboard/ledger

### Is this a build or a runtime issue?

Runtime

### Package Version

xyz

### What browsers are you seeing the problem on?

Chrome

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by taylorjdawson** [comment] 2022-09-09 20:47
hey @ziogaschr! Yes you are in the right spot! Does this only occur for you in Gnosis safe? Either way we'll take a look, if appropriate issue a fix, and update this issue with any details. 👍🏾 
Thanks for pointing this out!

**Comment by Adamj1232** [comment] 2022-09-09 21:10
@ziogaschr we are supporting Gnosis as they update to Onboard v2 (renamed Web3-Onboard) and I believe they are in the later stages of final testing. I can confirm this feature does work properly on W3O(Onboard v2) and returns the proper ETHC address. I will update here as that transition progresses!

**Comment by ziogaschr** [comment] 2022-09-09 21:34
Thanks a lot for the updates. 
@Adamj1232 is there an ETA you can share for when Gnosis Safe will release the new version with Onboard v2?

**Comment by Adamj1232** [comment] 2022-09-15 21:47
@ziogaschr I do not have an ETA but it seems they are moving along quickly. I will let you know when we hear about release with W3O support

**Comment by ziogaschr** [comment] 2022-09-21 19:23
Thanks a lot @Adamj1232

**Comment by Adamj1232** [comment] 2022-09-22 15:42
@ziogaschr We have released the fix for V1 and notified Gnosis. They said they are deprecating the current Safe and releasing a full rewrite at the beginning of October. That should help with this issue.
Since it will be handled on their end and we have the issue fixed and have notified platforms using Onboard I will close the issue for now. If any other issues arise please feel free to comment here. Thank you again!

**Closed by Adamj1232** 2022-09-22 15:42 UTC
Labels: bug

**Comment by ziogaschr** [comment] 2022-09-22 20:19
Thanks @Adamj1232. Great support, you've done what possible at your end, thanks.
