### ISSUE TITLE
useWallets did not return the expected on Server Render

### ISSUE THREAD

**Issue by lomocc** [blocknative/web3-onboard#1630] opened 2023-04-06 09:31 UTC
`useWallets` did not return the expected on `Server Render`. 
`stateKey` is missing.

```
const wallets = useWallets();
```
```
// output
{
    "wallets": [],
    "walletModules": [],
    "chains": [],
    ...
}
```
https://github.com/blocknative/web3-onboard/blob/2c8647c28426a7086c1988a1b32c2aa4cd6d5d52/packages/react/src/hooks/useAppState.ts#L31

**Comment by aaronbarnardsound** [comment] 2023-04-06 20:50
Hey @lomocc could you provide some more details on what the issue is that you are seeing?

**Comment by lomocc** [comment] 2023-04-07 02:24
https://codesandbox.io/p/sandbox/nostalgic-mirzakhani-e4x1pd?file=README.md

<img width="883" alt="image" src="https://user-images.githubusercontent.com/2075138/230528014-cd73186f-6e6d-4440-97bf-a8ba1a4926ed.png">

> Hey @lomocc could you provide some more details on what the issue is that you are seeing?

**Comment by lomocc** [comment] 2023-04-07 02:32
`getServerSnapshot` should return by `stateKey `

**Comment by aaronbarnardsound** [comment] 2023-04-10 20:44
Ah I see what you mean. Thanks for reporting, we'll get this fixed.

**Comment by Adamj1232** [comment] 2023-04-21 18:02
@lomocc this has been fixed with the latest version of the react package v2.8.0. Thank you for reporting!

**Closed by Adamj1232** 2023-04-21 18:02 UTC
Labels: bug
