### ISSUE TITLE
[Bug]: Gnosis Safe provider does not pick gas limit nor reports errors

### ISSUE THREAD

**Issue by enzoferey** [blocknative/web3-onboard#1255] opened 2022-09-07 07:53 UTC
### Current Behavior

When using the Gnosis Safe provider, the app does not pick the predefined gas limit for the transaction nor it throws an error when the execution of the transaction fails. It didn't use to be the case a few months ago.

### Expected Behavior

I expect the Safe App to pick the predefined gas limit I have computed for that transaction and to throw an error whenever the transaction execution fails.

### Steps To Reproduce

1. I'm using:

```
"@web3-onboard/react": "2.3.2",
"@web3-onboard/gnosis": "^2.1.2",
```

2. Go to https://gnosis-safe.io/ and create a safe for your app.
3. Then connect using the `@web3-onboard/gnosis` provider.
4. Start a transaction.
5. Notice the gas limit is not being picked up by the value you have computed before sending the transaction to the provider.

### What package is effected by this issue?

@web3-onboard/gnosis

### Is this a build or a runtime issue?

Runtime

### Package Version

2

### What browsers are you seeing the problem on?

Chrome

### Anything else?

The Safe App does report in the console the errors, however those are not surfaced to the application. I'm using `ethers@^5.7.0` and calling `await transaction.wait()` but the promise never resolves nor rejects.

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by taylorjdawson** [comment] 2022-09-12 19:47
@enzoferey Thanks for raising this issue! We'll take a look this week and see what the issue is!

**Comment by enzoferey** [comment] 2022-09-19 12:02
@taylorjdawson any updates ?

**Comment by RufusZero** [comment] 2022-10-07 11:01
Hey! This is an issue for me as well. Can anyone please take a look at this and/or report on the status?
Is this planned?

**Comment by aaronbarnardsound** [comment] 2022-10-10 01:55
We are going to take a look at this issue this week, we had a bit of a backlog to get through first.

**Comment by Adamj1232** [comment] 2022-10-13 20:34
@enzoferey @RufusZero can you send over the calls you are using to send the transaction?

**Comment by enzoferey** [comment] 2022-10-14 10:20
Hey @Adamj1232, here is a summary of what we are doing to generate the transaction (simplified React code, it won't work if you copy paste because of lifecycles):

```ts
// 1. We get a contract instance using Ethers and the provider obtained from @web3-onboard
const [{ wallet}] = useConnectWallet();
const connectedWalletProvider = new ethers.providers.Web3Provider(
        wallet.provider
);
const signer = provider.getSigner();
const contractInstance = new ethers.Contract(
    contractAddress,
    abi,
    signer
);

// 2. We populate the transaction setting a gas limit explicitly
const populatedTransaction = contractInstance.populateTransaction.someFunction(
    someArg1,
    someArg2,
    {
      gasLimit: 400000,
    }
);

// 3. We send the populated transaction via the signer and wait on it
const transaction = await signer.sendTransaction(populatedTransaction);
await transaction.wait();
```

After running that, see the gas limit is not being set to the amount specified:

<img width="539" alt="Screenshot 2022-10-14 at 11 04 24" src="https://user-images.githubusercontent.com/10673347/195808084-405e5d5b-1f08-428d-a103-14ed5a8f5984.png">

Then, about the transaction failure not being reported. If I execute the same transaction but set the gas limit low enough to force the transaction to fail, I see these errors in the console but the `transaction.wait()` call never resolves:

<img width="445" alt="Screenshot 2022-10-14 at 12 17 43" src="https://user-images.githubusercontent.com/10673347/195823469-f84b3ea9-f040-42a9-b360-939a26577b29.png">

You can see the transaction failed on MetaMask:

<img width="343" alt="Screenshot 2022-10-14 at 12 18 24" src="https://user-images.githubusercontent.com/10673347/195823590-d95b9572-0e04-4d0b-8a17-7ff70a21e82a.png">

And here is [the transaction](https://goerli.etherscan.io/tx/0xbfd5e44c9fb7739fb1f6a2ce26fe5f2eb63af24e040b07f8120e71c91bac5b32) on explorer.

While trying this, I have also found that if I set the `Nonce` value on the Advanced Parameters dialog, the transaction prompt I'm getting on the wallet does not use it but rather uses the next available one:

<img width="539" alt="Screenshot 2022-10-14 at 11 25 50" src="https://user-images.githubusercontent.com/10673347/195812490-a5aa81fc-1bcb-4041-85e0-2d8ace8b1d6a.png">

<img width="325" alt="Screenshot 2022-10-14 at 11 26 47" src="https://user-images.githubusercontent.com/10673347/195812701-a66135ae-d2bf-489d-bab1-306e0d51c1bb.png">

**Comment by Adamj1232** [comment] 2022-10-17 18:20
@enzoferey we have started a conversation with the Gnosis team around this as we are seeing the same behavior even with the usage of their SDK gas setting (`safeTxGas`) instance which is exposed through the gnosis wallet W3O instance.
More info available [here](https://www.npmjs.com/package/@gnosis.pm/safe-apps-sdk/v/6.1.1) under the Sending TXs section. I will update here as we make progress.

**Comment by enzoferey** [comment] 2022-10-17 18:53
Thanks for the update @Adamj1232 👍🏻

**Comment by Adamj1232** [comment] 2022-10-20 18:26
@enzoferey upon more discussion with the Gnosis team it seems gas estimation is send by their SDK and handled within the Safe. 
The Gnosis sdk instance exposed by the web3-onboard must be used to set the `safeTxGas` prop and send the transaction.
The behavior of `safeTxGas` depends on the `gasPrice` value of the Safe transaction.
Check [Gnosis docs](https://github.com/safe-global/safe-contracts/blob/a6504a9afdeac186a8cdb29ad68b189523c80eda/docs/safe_tx_gas.md) on this for full detail as it is a bit confusing.
An example of accessing the Gnosis SDK instance and sending a transaction can be found below.
```
    const tx = {
      to: toAddress,
      value: 1000000000000000,
      data: '0x',
    }
    const params = {
      safeTxGas: 5000000,
    };
    let trans = await wallet.instance.txs.send({txs:[tx], params})
```
Note: With the `safeTxGas` you will see additional value on the `gasLimit` displayed in the Safe. Check gnosis docs for full details there.
I will update with any further information on `gasLimit`/`safeTxGas`

**Comment by Adamj1232** [comment] 2022-10-20 18:32
@enzoferey can you detail the steps to create a failing transaction?
I am not able to reproduce through the Safe app within a browser.

**Comment by mikhailxyz** [comment] 2022-10-21 11:39
Hey, dev from the Safe team here. We do not support the ethereum transaction `gasLimit` (or, in fact, any other parameters for the ethereum transaction). The wallet will determine them at the time of the transaction execution.

**Comment by enzoferey** [comment] 2022-10-21 12:02
Hi @mikhailxyz, thanks for jumping in. Why are you not supporting any Ethereum transaction parameter ? Isn't that a big blocker for Safe apps development ?

@mikhailxyz If I understood well enough, you do have a dedicated `safeTxGas` field that behaves a bit differently than `gasLimit` that may allow playing around the gas limit issue. Is that correct ?

@Adamj1232 Would be setting this field on the `web3-onboard` provider propagate to the Safe as of today ?

@Adamj1232 To reproduce a failing transaction, just take any transaction, reduce its gas limit parameter on the Safe app dialog that opens up before asking for the wallet signature, ensure pressing the "simulate" button tells you the transaction will fail, and finally sign the transaction. It will revert because of the lack of gas and you will see the error is not being picked up by the `web3-onboard` provider.

**Comment by mikhailxyz** [comment] 2022-10-21 12:10
> Hi @mikhailxyz, thanks for jumping in. Why are you not supporting any Ethereum transaction parameter ? Isn't that a big blocker for Safe apps development ?

Why would it be a big blocker?

> @mikhailxyz If I understood well enough, you do have a dedicated safeTxGas field that behaves a bit differently than gasLimit that may allow playing around the gas limit issue. Is that correct ?

Yes, safeTxGas is the minimum gas that has to be supplied to the safe transaction.

**Comment by enzoferey** [comment] 2022-10-21 12:18
> Why would it be a big blocker?

Well, if a developer sets some values on the transaction like accurate gas prices or overwrite some previous transaction via the nonce value, you simply cannot.

**Comment by mikhailxyz** [comment] 2022-10-21 12:23
> > Why would it be a big blocker?
> 
> Well, if you want to set some values on the transaction like accurate gas prices or wants to overwrite some previous transaction via the nonce value, you simply cannot.

The wallet can calculate the gas limit, there's no justified reason to set it

**Comment by enzoferey** [comment] 2022-10-21 12:52
Wallet estimations on gas limit are way too often wrong. Gas limit cannot easily be computed via the classic approach when you are batching transactions and you have several proxy levels of delegate calls. Also, the gas limit of a certain operation might depend on the state of the contract and you sometimes want to provider a higher gas limit than reported at the current moment to protect yourself against front running or activity spikes.

Wallet estimations on gas price are also way too often wrong. They would be computed based on some unique algorithm defined by the wallet which some times has flaws itself or just does not fit your dApp needs. That's where providing suggestions makes a lot of sense so users can have a better experience.

**Comment by mikhailxyz** [comment] 2022-10-21 13:07
> Wallet estimations on gas limit are way too often wrong. Gas limit cannot easily be computed via the classic approach when you are batching transactions and you have several proxy levels of delegate calls. Also, the gas limit of a certain operation might depend on the state of the contract and in those cases you want to provide a higher gas limit to protect yourself against front running or activity spikes. Having a "minimum gas spent" approach is the opposite way of how it has been designed at the chain level and I believe should not the preferred way for setting a transaction gas limit. It is useful in certain scenarios, but it should not be the only way.
> 
> Wallet estimations on gas price are also way too often wrong. They would be computed based on some unique algorithm defined by the wallet which some times has flaws itself or just does not fit your dApp needs. That's where providing suggestions makes a lot of sense so users can have a better experience.

I (somewhat) understand you, but I can say the same thing: dApp estimations on gas prices and gas limits are also way too often wrong. Especially for smart contract wallets

**Comment by mikhailxyz** [comment] 2022-10-21 16:32
> @mikhailxyz thank you for chiming in! I am trying to catch the 803 event(or the error message more closely related to the error occurring) from the Safe to pass along through the provider. The error seems to always be converted to `Error: Transaction was rejected` even if the transaction was canceled in the wallet or there was a gas error. Do you know if there is way to get the `intrinsic gas too low` error message from the Safe so it can be passed through the Web3-Onboard package? It seems in this case the MetaMask error is being caught by the Safe and not passed. <img alt="Screen Shot 2022-10-21 at 10 25 24 AM" width="1323" src="https://user-images.githubusercontent.com/24457880/197243641-cfb9837b-a62f-47f7-ac0d-6a54f7d610e3.png">

I'm not sure what's the problem here, the error happened after the "transaction was rejected" error that was returned by the SDK. So why would it be passed? Perhaps I do not understand the problem very well.

**Comment by Adamj1232** [comment] 2022-10-21 16:50
> > @mikhailxyz thank you for chiming in! I am trying to catch the 803 event(or the error message more closely related to the error occurring) from the Safe to pass along through the provider. The error seems to always be converted to `Error: Transaction was rejected` even if the transaction was canceled in the wallet or there was a gas error. Do you know if there is way to get the `intrinsic gas too low` error message from the Safe so it can be passed through the Web3-Onboard package? It seems in this case the MetaMask error is being caught by the Safe and not passed. <img alt="Screen Shot 2022-10-21 at 10 25 24 AM" width="1323" src="https://user-images.githubusercontent.com/24457880/197243641-cfb9837b-a62f-47f7-ac0d-6a54f7d610e3.png">
> 
> I'm not sure what's the problem here, the error happened after the "transaction was rejected" error that was returned by the SDK. So why would an error happening later be passed? Perhaps I do not understand the problem very well.

Apologies sent, the wrong screenshot. The error occurs before the SDK return the `Transaction was rejected` after the `intrinsic gas too low` error but that verbiage isn't passed along with the error object.
<img width="1033" alt="Screen Shot 2022-10-21 at 10 43 15 AM" src="https://user-images.githubusercontent.com/24457880/197246978-01cd5dbe-e94a-4f59-8aa6-e9e9127641de.png">
 Code producing err for context. Happens both with `SDK.txs.send` and using the bare with `eth_sendTransaction`
```
eth_sendTransaction: async ({baseRequest, txs}) => {
  try {
    const transactionHash = await appsSdk.txs.send({txs})
    return transactionHash
  } catch (e) {
    console.log(e)
  }
}
```

**Comment by enzoferey** [comment] 2022-10-21 17:02
> I (somewhat) understand you, but I can say the same thing: dApp estimations on gas prices and gas limits are also way too often wrong. Especially for smart contract wallets

@mikhailxyz Agreed too, OpenSea being one of them as an example. The difference is that you are leaving place for dApp to make their own judgements and go for your recommendations or stick with theirs. As of right now, dApps are forced to follow your recommendations, which fall short for our business as an example. Hope this conversation makes you reconsider this topic or at least start a conversation about it internally. Thank you again for your help here 😁

**Comment by mikhailxyz** [comment] 2022-10-22 08:57
> > I (somewhat) understand you, but I can say the same thing: dApp estimations on gas prices and gas limits are also way too often wrong. Especially for smart contract wallets
> 
> @mikhailxyz Agreed too, OpenSea being one of them as an example. The difference is that you are leaving place for dApp to make their own judgements and go for your recommendations or stick with theirs. As of right now, dApps are forced to follow your recommendations, which fall short for our business as an example. Hope this conversation makes you reconsider this topic or at least start a conversation about it internally. Thank you again for your help here 😁

Could you please share an example of a transaction where Safe fails to estimate gas? We'd like to fix our estimation in the first place.

**Comment by mikhailxyz** [comment] 2022-10-22 09:00
> > > @mikhailxyz thank you for chiming in! I am trying to catch the 803 event(or the error message more closely related to the error occurring) from the Safe to pass along through the provider. The error seems to always be converted to `Error: Transaction was rejected` even if the transaction was canceled in the wallet or there was a gas error. Do you know if there is way to get the `intrinsic gas too low` error message from the Safe so it can be passed through the Web3-Onboard package? It seems in this case the MetaMask error is being caught by the Safe and not passed. <img alt="Screen Shot 2022-10-21 at 10 25 24 AM" width="1323" src="https://user-images.githubusercontent.com/24457880/197243641-cfb9837b-a62f-47f7-ac0d-6a54f7d610e3.png">
> > 
> > 
> > I'm not sure what's the problem here, the error happened after the "transaction was rejected" error that was returned by the SDK. So why would an error happening later be passed? Perhaps I do not understand the problem very well.
> 
> Apologies sent, the wrong screenshot. The error occurs before the SDK return the `Transaction was rejected` after the `intrinsic gas too low` error but that verbiage isn't passed along with the error object. <img alt="Screen Shot 2022-10-21 at 10 43 15 AM" width="1033" src="https://user-images.githubusercontent.com/24457880/197246978-01cd5dbe-e94a-4f59-8aa6-e9e9127641de.png"> Code producing err for context. Happens both with `SDK.txs.send` and using the bare with `eth_sendTransaction`
> 
> ```
> eth_sendTransaction: async ({baseRequest, txs}) => {
>   try {
>     const transactionHash = await appsSdk.txs.send({txs})
>     return transactionHash
>   } catch (e) {
>     console.log(e)
>   }
> }
> ```

We'll check this. Agree the error message could be improved

**Comment by Adamj1232** [comment] 2022-10-24 22:45
> Could you please share an example of a transaction where Safe fails to estimate gas? We'd like to fix our estimation in the first place.

Blocknative has a Simulation platform/endpoint with a really solid record, if interested let me know @mikhailxyz

**Comment by mikhailxyz** [comment] 2022-10-27 16:18
> > > @mikhailxyz thank you for chiming in! I am trying to catch the 803 event(or the error message more closely related to the error occurring) from the Safe to pass along through the provider. The error seems to always be converted to `Error: Transaction was rejected` even if the transaction was canceled in the wallet or there was a gas error. Do you know if there is way to get the `intrinsic gas too low` error message from the Safe so it can be passed through the Web3-Onboard package? It seems in this case the MetaMask error is being caught by the Safe and not passed. <img alt="Screen Shot 2022-10-21 at 10 25 24 AM" width="1323" src="https://user-images.githubusercontent.com/24457880/197243641-cfb9837b-a62f-47f7-ac0d-6a54f7d610e3.png">
> > 
> > 
> > I'm not sure what's the problem here, the error happened after the "transaction was rejected" error that was returned by the SDK. So why would an error happening later be passed? Perhaps I do not understand the problem very well.
> 
> Apologies sent, the wrong screenshot. The error occurs before the SDK return the `Transaction was rejected` after the `intrinsic gas too low` error but that verbiage isn't passed along with the error object. <img alt="Screen Shot 2022-10-21 at 10 43 15 AM" width="1033" src="https://user-images.githubusercontent.com/24457880/197246978-01cd5dbe-e94a-4f59-8aa6-e9e9127641de.png"> Code producing err for context. Happens both with `SDK.txs.send` and using the bare with `eth_sendTransaction`
> 
> ```
> eth_sendTransaction: async ({baseRequest, txs}) => {
>   try {
>     const transactionHash = await appsSdk.txs.send({txs})
>     return transactionHash
>   } catch (e) {
>     console.log(e)
>   }
> }
> ```

I've just checked this, and everything looks fine on our end. Gas estimation failure doesn't reject the transaction, and the user still can put a custom gas limit and execute the transaction.

**Comment by Adamj1232** [comment] 2022-10-28 15:04
@mikhailxyz ah ok, it is strange that the Code 803 is not surfaced through the catch. I would expect the 803 code to be propagated. I have updated our documentation around gas usage and pointing to your docs. I will close for now. Thank you for looking.

**Comment by mikhailxyz** [comment] 2022-10-28 22:05
> @mikhailxyz ah ok, it is strange that the Code 803 is not surfaced through the catch. I would expect the 803 code to be propagated. I have updated our documentation around gas usage and pointing to your docs. I will close for now. Thank you for looking.

Why would it be?🤔 the error doesn't stop the transaction sending process. You can still execute the transaction

**Comment by enzoferey** [comment] 2022-10-29 21:59
Great you updated the docs @Adamj1232 👌🏻 

What about transaction execution failures not being propagated to the web3-onboard Gnosis provider ? I don't think your back and forth these past few days have come to any result. As @mikhailxyz said you should be able to execute the transaction, but if it ends up failing for whatever reason during execution the web3-onboard Gnosis provider should be throwing while awaiting for the transaction minting.

**Comment by Adamj1232** [comment] 2022-10-31 18:12
@mikhailxyz the expected behavior is to have uncaught promises?
I understand that there is async nature but shouldnt the promise resolve with the error?
I was unable to get a Safe transaction hash when using either method(SDK or `eth_sendTransaction`) returned - as seen in the video.
You can see in both instances no error makes it out of the Gnosis provider or the SDK function.
Apologies for pushing on the issue but this is a UX issue for users and without those errors there is no way for dapps to handle accordingly.

**Comment by mikhailxyz** [comment] 2022-10-31 18:27
> @mikhailxyz the expected behavior is to have uncaught promises?
> I understand that there is async nature but shouldnt the promise resolve with the error?
> I was unable to get a Safe transaction hash when using either method(SDK or `eth_sendTransaction`) returned - as seen in the video.
> You can see in both instances no error makes it out of the Gnosis provider or the SDK function.
> Apologies for pushing on the issue but this is a UX issue for users and without those errors there is no way for dapps to handle accordingly.

Ahh, sorry, I misunderstood the video 🙈 that definitely needs a fix. Do I understand correctly that you expect it to throw with the metamask's error message (intrinsic gas too low)?

**Comment by mikhailxyz** [comment] 2022-11-04 12:38
@Adamj1232 we'll release a new app later this month, and it seems the SDK error reporting won't be a problem anymore because we'll handle all the errors in the wallet itself. Please see the video:

https://www.loom.com/share/55c80b3608c641cea8ec5be4f3796730

**Comment by Adamj1232** [comment] 2022-11-04 15:42
@mikhailxyz thank you for your response and the video! Its very helpful. I will go ahead and close this issue as the app will be handling the errors after release. Thank you again!

**Closed by Adamj1232** 2022-11-04 15:42 UTC
Labels: bug

**Comment by enzoferey** [comment] 2022-11-05 00:21
Sorry for the silence these last few days guys. Thank you the Loom video @mikhailxyz , it was very illustrative. Thank you also @Adamj1232 for your patience 🙏🏻
