### ISSUE TITLE
a disconnect error by default value or other reason can not set local storage

### ISSUE THREAD

**Issue by logsdk** [blocknative/web3-onboard#2227] opened 2024-06-10 08:07 UTC
### Current Behavior

1、connect wallet, tips successful
2、discount wallet, error

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at disconnect (index-34745058.js:3597:25)
    at async eval (useConnectWallet.js:25:29)

in packages/core/src/disconnect.ts:47
```javascript
const labels = JSON.parse(getLocalStore(STORAGE_KEYS.LAST_CONNECTED_WALLET) || '');
```
if can not get last connected wallet, the default value '', can not be parsed by JSON.

### Expected Behavior

disconnect wallet successful

### What package is effected by this issue?

@web3-onboard/core

### Is this a build or a runtime issue?

Runtime

### Package Version

2.22.1

### Sanity Check

- [x] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by ignromanov** [comment] 2024-06-13 21:02
Hi. 
The same issue.
You need to connect to the DApp using Rabby wallet.
After pressing the disconnect button (calling the disconnect function) - an error is thrown.
```ts
  const [{ wallet }, disconnect] = useConnectWallet()
  await disconnect(wallet)
```
The reason is that the `onboard.js:last_connected_wallet` key is missing from the local storage

**Comment by Adamj1232** [comment] 2024-06-13 21:19
@ignromanov Disconnect using the approach as shown above working without issue on our demo sites - https://github.com/blocknative/react-demo/blob/89509379f4cd09299b45b2301769aa80a7c58991/src/App.js#L543
If you can provide more code for context I can assist further

**Comment by ignromanov** [comment] 2024-06-14 13:31
The reason was that flags `autoConnectLastWallet` and `autoConnectAllPreviousWallet` were false during onboard initialization

**Comment by Adamj1232** [comment] 2024-06-14 18:57
@ignromanov does that mean we can close this issue?

**Comment by ignromanov** [comment] 2024-06-14 20:04
@Adamj1232 I think you should test with these flags set to False. You will get a disconnect error.

**Comment by Adamj1232** [comment] 2024-06-14 20:19
@ignromanov I am still unable to reproduce the disconnect error - I made a video of what I am seeing when trying this locally. https://www.loom.com/share/3d73a7ccfa1645cb9deb820fb8ea438c?sid=93f5efb4-5539-4075-a204-c9ea9dcea605
Might be good to confirm you are on the latest version of `"@web3-onboard/injected-wallets": "^2.11.1"`

**Comment by ignromanov** [comment] 2024-06-14 20:44
@Adamj1232 I tried it on your test application. Try with these changes to reproduce it. I got an error.

<img width="332" alt="image" src="https://github.com/blocknative/web3-onboard/assets/3179314/ecf69bb2-9837-411f-a327-8f33bce5eaf8">

**Comment by Adamj1232** [comment] 2024-06-14 21:12
@ignromanov I am still unable to reproduce an error with that change

**Comment by ignromanov** [comment] 2024-06-14 22:02
@Adamj1232 Recorded a video reproduction of the error. Launched your repository with the change described above.

https://github.com/blocknative/web3-onboard/assets/3179314/c4428a70-e6ae-4056-909e-0adf7bf19bdb

**Comment by satoshisafedevs** [comment] 2024-06-16 20:41
We are seeing this same issue with the latest version on all packages and brave browser.

**Comment by Adamj1232** [comment] 2024-06-17 16:51
@ignromanov ahh ok I think I got it figured out, required a local storage clear to reproduce. Looking into this today. Will have a fix shortly.

**Closed** 2024-06-17 18:00 UTC
Labels: bug

**Comment by Adamj1232** [comment] 2024-06-17 18:02
@ignromanov please give this a shot with the latest alpha version of @web3-onboard/core or framework package noted in the PR above - would love validation on your end prior to release
