### ISSUE TITLE
[Bug]: selectAccounts(existingWallet.provider) always throws error

### ISSUE THREAD

**Issue by danpetban** [blocknative/web3-onboard#888] opened 2022-03-21 09:55 UTC
### Current Behavior

`selectAccounts(existingWallet.provider)` always throws errors, because the provider implementations.  

As I can see, all of it just implement the following:
`eth_selectAccounts: UNSUPPORTED_METHOD`

According to this, the `actionRequired` value will be `true` and the modal appears.

### Expected Behavior

Just because the provider does not have a `eth_selectAccounts` method, don't show the modal every time.

### Onboard Version

core: 2.0.11, injected: 2.0.2

### Node Version

16

**Comment by aaronbarnardsound** [comment] 2022-04-01 02:15
Hey @band94, the idea with that modal is that when the user selects a wallet that they are already connected to, then their intention is to connect another account for that wallet. In the case of hardware wallets, we have control of the UI, so we can show the user the account select options. That is what we created the `eth_selectAccounts` RPC method for. In the case of other wallets that we do not have control of the UI, then that method is not implemented (since we made it up), so in that case we display the modal to guide the user to connecting another account.

Are you trying to call the `eth_selectAccounts` method directly?

**Comment by aaronbarnardsound** [comment] 2022-04-06 06:19
Going to close this for now as that is expected behavior. Feel free to reopen if you have further questions.

**Comment by Holybasil** [comment] 2022-11-15 06:39
@aaronbarnardsound Thanks for your explanation, pretty helpful 🎉

**Comment by Dinuz** [comment] 2022-12-17 21:12
@aaronbarnardsound This makes sense if you look at it as you did. However this becomes an annoying issue if you are trying to reconnect a wallet that you stored in the localstorage for example.
In my case I was trying to "persist" a wallet connection after a page refresh, and in discord someone of the team suggested to look at the implementation of Auto Selecting a Wallet in the core documentation.
Following the example I was able to set a localstorage look up and so automatically persist the wallet connection despite the browser page refresh (this is great because makes a better ux, removing the need to re-click on the connecting button after refresh).
I was very happy with the solution until I discovered that if something gets updated reactively, then the solution triggers the popup and Action Required.
This clearly in my case is pointless, because there isn't any switch of wallet. How I solve or disable this?

I am using the VUE plugin, and my code is something like the following:

const walletInitializer = async () => {
    const previouslyConnectedWallets = JSON.parse(
      window.localStorage.getItem('alreadyConnectedWallets')
    )
    if (previouslyConnectedWallets[0]) {
      try {
        await connectWallet({
          autoSelect: {
            label: previouslyConnectedWallets[0],
            disableModals: true,
          },
        })
      } catch (error) {
        console.log('Houston we got a problem!', error.error)
      }
    }
  }

**Comment by aaronbarnardsound** [comment] 2022-12-18 20:56
Hey @Dinuz could you elaborate on what is getting updated reactively that triggers that modal? Could you try connecting a wallet and then refreshing on our [React Demo](https://reactdemo.blocknative.com) and see if you see the same behaviour? We don't have the `disableModals` flag set in the demo, but I just tried locally with that flag set and everything works as expected.

**Comment by Dinuz** [comment] 2022-12-19 22:40
@aaronbarnardsound yeah, in my frontend I do have a way to setup an options array that goes directly into the composable in which I have the previous function (the one in my previous post walletInitializer) defined. The options are used to control the composable behavior (for example I can change the min balance required in order for the user to be able to perform some operations eg mint). Every time that I change one of these options I do have the popup coming out with the following message: 

<img width="1410" alt="Screen Shot 2022-12-19 at 5 34 15 PM" src="https://user-images.githubusercontent.com/1139472/208539898-1c07ef2c-d7f6-477c-b7e0-08c65cf0470b.png">

<img width="372" alt="Screen Shot 2022-12-19 at 5 34 28 PM" src="https://user-images.githubusercontent.com/1139472/208539912-8477aaf1-0506-4a87-8181-cfacb7fe72b3.png">

I found a way to kill this but I am not sure it is the most beautiful and appropriate way to do so: I call the disconnect wallet just before connecting it again (to be truly honest I don't like this at all, but it removes the error and prevents the popup to showing up). So If I modify the previous function in the following way, my problem gets solved:

```
const walletInitializer = async () => {
    const previouslyConnectedWallets = JSON.parse(
      window.localStorage.getItem('alreadyConnectedWallets')
    )

    if (previouslyConnectedWallets[0]) {
      try {
        await disconnectWallet({ label: previouslyConnectedWallets[0] }) // I ADD THIS NEW LINE
        await connectWallet({
          autoSelect: {
            label: previouslyConnectedWallets[0],
            disableModals: true,
          },
        })
      } catch (error) {
        console.log('Cannot initialize the wallet!', error.error)
      }
    }
  }


```

What do you think? Suggestions? Opinions? Yelling at me lol? 

Thanks :)

**Comment by katspaugh** [comment] 2023-01-06 15:06
As others mentioned here, this popup appears even when you don't want to select another account but rather another wallet.

Consider this use case:

* User is connected to an app with MetaMask
* They then decide to switch to their mobile wallet via WalletConnect
* Potentially switch back to the first wallet

In this case, we would call `connectWallet()` w/o specifying a wallet, so that the user can choose one.

<img width="476" alt="Screenshot 2023-01-06 at 16 03 57" src="https://user-images.githubusercontent.com/381895/211038825-f6bbf81b-7b39-4aad-9338-ad5581505f70.png">

And then this annoying popup appears, which actually does nothing. And an error in the console.

<img width="742" alt="Screenshot 2023-01-06 at 16 05 07" src="https://user-images.githubusercontent.com/381895/211039046-71b1852e-0297-416a-862b-4592b77f2ea2.png">

Do you think we could avoid showing this popup unless the app explicitly asks to switch the account within the same wallet?

**Comment by aaronbarnardsound** [comment] 2023-01-09 20:20
We'll be taking another look at this issue as we have had multiple reports of this.

**Comment by jamesmorgan** [comment] 2023-01-11 17:47
Also seeing this issue - vue/nuxt

**Closed** 2023-03-30 20:45 UTC
Labels: bug
