### ISSUE TITLE
[Bug]: Vite / Ledger doesn't seem to work together

### ISSUE THREAD

**Issue by WoodyDark** [blocknative/web3-onboard#1377] opened 2022-11-23 06:06 UTC
### Current Behavior

When attempting to submit a transaction, it errors out with
```
index.js:3098 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'Berlin')
    at getCommon (index.js:3098:28)
    at async Object.eth_signTransaction (index.js:192:40)
    at async Object.eth_sendTransaction (index.js:221:42)
```

![image](https://user-images.githubusercontent.com/40813266/203481534-870c9b39-6b4d-4fb2-aea0-9ff42db60696.png)

### Expected Behavior

It should submit the transaction without any issues

### Steps To Reproduce

I've recreated the issue in this repo, just `npm i` and `npm run dev` to run. After connecting a Ledger wallet, it should try to submit a transaction and fail immediately. The error will show up in the console.

https://github.com/WoodyDark/web3-onboard-vite-ledger/blob/main/src/App.vue

### What package is effected by this issue?

@web3-onboard/ledger

### Is this a build or a runtime issue?

Runtime

### Package Version

2.10.1

### Node Version

16.18.0

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
index.js:3098 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'Berlin')
    at getCommon (index.js:3098:28)
    at async Object.eth_signTransaction (index.js:192:40)
    at async Object.eth_sendTransaction (index.js:221:42)
```

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by Adamj1232** [comment] 2023-01-11 21:43
@WoodyDark friendly ping, are you still encountering this issue?
We recently partnered with Ledger to create a new package version with all new deps using the latest Ledger applications and I would be interested to hear if that fixes your problem.

**Comment by Adamj1232** [comment] 2023-01-26 19:26
Closing as we are unable to reproduce this issue and the Ledger package has been updated by the Ledger team

**Closed by Adamj1232** 2023-01-26 19:26 UTC
Labels: bug
