### ISSUE TITLE
Metamask connects the wrong wallet

### ISSUE THREAD

**Issue by lososeg** [blocknative/web3-onboard#1880] opened 2023-08-16 03:23 UTC
### Current Behavior

When connecting via Metamask, not the active wallet is used, but the one that was connected before.

### Steps To Reproduce

Error can be reproduced on the website https://onboard.blocknative.com/
1. disconnect all wallets from the site in Metamask
![image](https://github.com/blocknative/web3-onboard/assets/29502537/b23a97a4-039a-41ec-88cb-546bdd717051)
2. connect first wallet to the site
3. disconnect it by clicking button on the site
4. switch in Metamask to another wallet
5. connect second wallet to the site
6. library automatically connects first wallet that is not currently active in Metamask

### What package is effected by this issue?

@web3-onboard/react

### Is this a build or a runtime issue?

Runtime

### Package Version

2.7.1

### Node Version

18.12.1

### What browsers are you seeing the problem on?

Chrome

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by leightkt** [comment] 2023-08-16 14:59
@lososeg this sounds like a case of wallets fighting for the window.ethereum space- you can read more and access troubleshooting tips [here](https://onboard.blocknative.com/docs/resources/troubleshooting#_2-multiple-wallets-installed)

**Comment by lososeg** [comment] 2023-08-17 19:10
> @lososeg this sounds like a case of wallets fighting for the window.ethereum space- you can read more and access troubleshooting tips [here](https://onboard.blocknative.com/docs/resources/troubleshooting#_2-multiple-wallets-installed)

No, I have only metamask installed (with several addresses) and I tested it in a private tab in which I allowed only metamask

**Comment by leightkt** [comment] 2023-08-17 23:46
@lososeg are you talking about Accounts within Metamask? Can you send a video of an example?

**Comment by lososeg** [comment] 2023-08-18 06:56
This is video of the error
https://github.com/blocknative/web3-onboard/assets/29502537/5c3e8715-9107-4fd3-b704-939e8d93e4b4

**Comment by leightkt** [comment] 2023-08-18 15:42
@lososeg Thank you for the video- it's very helpful. We'll add to the team's backlog and keep you updated as we look into it.

**Comment by Adamj1232** [comment] 2023-08-23 19:06
@lososeg this is expected behavior as you only gave access to that one account that reconnected on the initial MetaMask connect accounts screen and also why we display this message in the connect modal about selecting all accounts you wish to grant access to.
<img width="1287" alt="Screenshot 2023-08-23 at 1 03 50 PM" src="https://github.com/blocknative/web3-onboard/assets/24457880/90ba37b8-99af-42e3-8b15-b8b599430b1e">
If access is granted to the other wallet it will connect to that account. This is also something we dont have control over as the MetaMask provider doesnt emit events on which account is currently active but returns all accounts that are available for the provider.
Closing for now as this is not a bug we have control of. Please feel free to continue the conversation

**Closed by Adamj1232** 2023-08-23 19:06 UTC
Labels: bug
