### ISSUE TITLE
Font size conflict

### ISSUE THREAD

**Issue by Tiago138** [blocknative/web3-onboard#1856] opened 2023-07-31 18:26 UTC
### Current Behavior

In our project we use rem but we define the global size of the font to ```font-size: 62.5%;``` and web3onboard app uses rem, but since it does not take in consideration that we are changing the font size the interface looks broken. And it does not seems to be possible to change some styles.
You can check how it looks on or [app](https://app.kassandra.finance/)

### Expected Behavior

Is expected that the interface does not looks broken.

### Steps To Reproduce

1. in the html tag change the font-size to 62.5%.
``` css
html {
    font-size: 62.5%;
}
```

### What package is effected by this issue?

@web3-onboard/react

### Is this a build or a runtime issue?

Runtime

### Package Version

2.8.10

### Node Version

18.17.0

### What browsers are you seeing the problem on?

Firefox, Chrome

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by leightkt** [comment] 2023-08-04 18:45
@Tiago138 Thanks for reporting. This looks like a duplicate of #1755 ?

**Comment by taylorjdawson** [comment] 2023-08-12 23:00
@Tiago138 If you're okay with it, I will close this issue in leu of #1755, and you can track the conversation there 👍

**Closed by taylorjdawson** 2023-08-12 23:00 UTC
Labels: bug

**Comment by Tiago138** [comment] 2023-08-14 12:34
> @Tiago138 If you're okay with it, I will close this issue in leu of #1755, and you can track the conversation there +1

OK, thanks.
