### ISSUE TITLE
[Bug]: Unstoppable Domains resolution error

### ISSUE THREAD

**Issue by gretzke** [blocknative/web3-onboard#1513] opened 2023-02-05 01:36 UTC
### Current Behavior

When connecting a wallet onboard tries to call the Unstoppable Domains contracts on Ethereum and Polygon using a custom Infura endpoint. These requests fail with the following error: "rejected due to project ID settings".

### Expected Behavior

The calls should either not fail or there should be an option to disable Unstoppable Domains support in the init config

### Steps To Reproduce

```
const injected = injectedModule({});

this.onboard = Onboard({
  wallets: [injected],
  chains: blockNativeChains,
  appMetadata: {
    ...
  },
});
```

Connect to wallet via `await this.onboard.connectWallet();`
The errors will show up in the console

### What package is effected by this issue?

@web3-onboard/core

### Is this a build or a runtime issue?

Runtime

### Package Version

2.14.1

### Node Version

16.17.1

### What browsers are you seeing the problem on?

Firefox, Chrome

### Relevant log output

```shell
ResolutionError: < Request to https://mainnet.infura.io/v3/c4bb906ed6904c42b19c95825fe55f39 failed with response status 403 >
```

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by Adamj1232** [comment] 2023-02-05 01:49
@gretzke thank you for reporting this issue! 
Can you send a screenshot of the error in the console? 
I'm unable to replicate the error with the provided code.

**Comment by gretzke** [comment] 2023-02-05 03:47
![image](https://user-images.githubusercontent.com/10338391/216800429-3be383d3-e8a4-404f-9abc-3152e387dfce.png)
this is on my localhost

alternatively you can go to https://easyd.app/ , connect your wallet and check out the console

**Comment by gretzke** [comment] 2023-02-05 04:03
Interestingly enough, exploring the demo project, I noticed some differences, for once in the UI:

![image](https://user-images.githubusercontent.com/10338391/216800761-ab616ad5-c781-4cf2-ae4d-b8cfee03175a.png)

this is how my wallet selection looks like on mobile, compared to the demo project where it looks normal.

Also the demo project shows more wallet options than the default injected object, but I don't know which are configured manually and which are not.

I'm using Angular, which isn't a framework used very often in this industry I feel, maybe this is introducing some inconsistencies?

**Comment by amrap030** [comment] 2023-02-06 01:09
I have the same problem with a fresh installation of `@web3-onboard/vue` and `@web3-onboard/injected-wallets` today.

<img width="809" alt="Bildschirmfoto 2023-02-06 um 02 07 39" src="https://user-images.githubusercontent.com/35061229/216859367-40540f43-4699-4745-9463-d2d48f2b7722.png">

The error was probably introduced in some of the newer versions.

**Comment by Adamj1232** [comment] 2023-02-06 16:11
@gretzke thank you for the further context - what framework are you using? 
Can you try upgrading node to v18 just for a test on the polyfill front? I am trying to reproduce
@amrap030 thank you also for the further context - which version of node are you using?
A local reproduce-able example would be very helpful if either of you have one

**Comment by gretzke** [comment] 2023-02-06 16:53
I'm using Angular, tried using node v18, same issue persists

**Comment by Adamj1232** [comment] 2023-02-06 17:02
@gretzke ah good to know and the `c4bb906...` infura ID shown is not your infura api key?

**Comment by gretzke** [comment] 2023-02-06 17:03
nope, I'm not using infura in my project

**Comment by amrap030** [comment] 2023-02-06 17:11
In my error it is the same infura api key, which is also not mine. I am already using node v18.

You should be able to reproduce it from my repo: https://github.com/amrap030/c2d-marketplace

At the root run `yarn install` then change directory to `src/marketplace` and run `yarn dev`

**Comment by gretzke** [comment] 2023-02-06 18:11
Tracking the stack trace the call seems to revert inside the `@unstoppabledomains/resolution` package. I tried recreating the issue in a brand new repo and so far I wasn't able to.

In the meantime here is my repo: https://github.com/gretzke/easy-dapp
`npm install` and `ng serve --configuration=production` to see the issue

**Comment by n4n0GH** [comment] 2023-02-07 07:22
That API key is used by Resolution https://github.com/unstoppabledomains/resolution/blob/master/src/UnsInternal.ts#L27 and whatever setting they're using in their Infura backend is preventing this from being usable at all.

![Screenshot 2023-02-07 at 8 22 07 AM](https://user-images.githubusercontent.com/27410256/217175648-826b6fae-be2c-457c-83a5-449c8d2202ce.png)

**Comment by n4n0GH** [comment] 2023-02-07 07:48
So basically web3-onboard needs to provide a method to inject our own API keys into Resolution, as per their documentation:

![image](https://user-images.githubusercontent.com/27410256/217183343-0f7e105d-bdaf-4340-ae24-72b6b00f0d9f.png)
https://github.com/unstoppabledomains/resolution/blob/master/README.md#custom-ethereum-provider-configuration

**Comment by Adamj1232** [comment] 2023-02-07 15:50
Thanks for all the feedback and digging! We are looking into this with the unstoppable domains team - @V-Shadbolt
We will update here as this progresses

**Comment by V-Shadbolt** [comment] 2023-02-07 18:49
Hey all! 

This issue should be fixed now and is no longer reproducible on [https://easyd.app/](https://easyd.app/) mentioned above. We recently moved from Alchemy to Infura and it seems a config was missed on this key. We did the update on our end so no need to make any changes to your repos.

**Comment by Adamj1232** [comment] 2023-02-07 19:07
Thank you @V-Shadbolt !
Closing for now as the issue is resolved. Feel free to continue commenting here or open another issue if anything else arises. Thanks all!!

**Comment by n4n0GH** [comment] 2023-02-25 19:47
This error is happening again; the limit for your infura endpoint is reached and requests are being blocked.

**Comment by Adamj1232** [comment] 2023-02-26 16:42
@n4n0GH Thanks for raising this issue! We have passed along to our connections at unstoppable and will update shortly on progress
Ping @V-Shadbolt

**Comment by hans-crypto** [comment] 2023-02-27 12:51
This error is really inconvenient and this is not the first time it happens. Is there any way to disable Unstoppable Domains  once and for all?

**Comment by Adamj1232** [comment] 2023-02-27 16:42
> This error is really inconvenient and this is not the first time it happens. Is there any way to disable Unstoppable Domains once and for all?

We will look into adding a config to make this resolution optional. Apologies for the issue. We are working with the UD team to resolve

**Comment by Adamj1232** [comment] 2023-02-27 18:05
> This error is really inconvenient and this is not the first time it happens. Is there any way to disable Unstoppable Domains once and for all?

Do you (or @n4n0GH ) happen to have a reproducible example that we can see this issue? If not some log screenshots would be helpful as well! Thank you!

**Comment by hans-crypto** [comment] 2023-02-27 18:47
> > This error is really inconvenient and this is not the first time it happens. Is there any way to disable Unstoppable Domains once and for all?
> 
> Do you (or @n4n0GH ) happen to have a reproducible example that we can see this issue? If not some log screenshots would be helpful as well! Thank you!

I think the reason for the problem is known. In a dependency of Unstoppable Domains is a default API key for Infura. (see here https://github.com/unstoppabledomains/resolution/blob/master/src/UnsInternal.ts#L27)

Short term solution: Make resolver for UD disableable. (Maybe for ENS, too. just to be sure!)
Long term solution: It should be possible to specify an own API key.

**Comment by hans-crypto** [comment] 2023-02-27 18:51
Feel free to login here to see the error: https://genesis.haushoppe.art/ (change to Goerli first) to see the error.


<img width="789" alt="Screenshot 2023-02-27 at 19 48 56" src="https://user-images.githubusercontent.com/108269257/221655781-67617835-653d-4cf3-841f-425463a76e04.png">
<img width="760" alt="Screenshot 2023-02-27 at 19 49 14" src="https://user-images.githubusercontent.com/108269257/221655799-5eabef1c-d978-4f61-bc18-fdd10888ad9a.png">

**Comment by aaronbarnardsound** [comment] 2023-02-28 03:56
Yeah it looks like we should be passing in the `rpcUrl`'s in when creating the `Resolution` object on [this line](https://github.com/blocknative/web3-onboard/blob/develop/packages/core/src/provider.ts#L391):

```javascript
// custom provider config using the `Resolution` constructor options
const resolution = new Resolution({
    sourceConfig: {
      uns: {
        locations: {
          Layer1: {
            url: ethereumProviderUrl,
            network: 'mainnet'
          },
          Layer2: {
            url: polygonProviderUrl,
            network: 'polygon-mainnet',
          },
        },
      },
    },
  });
```

I'll see if I can get a PR happening this week, most of our devs are at EthDenver. Otherwise if anyone else wants to PR and test I would be happy to review!

**Comment by n4n0GH** [comment] 2023-02-28 12:26
Sounds about right, as I mentioned before: https://github.com/blocknative/web3-onboard/issues/1513#issuecomment-1420335507

But making the Resolution module optional would ideally be the best short-term fix.

**Closed** 2023-02-28 20:16 UTC
Labels: bug
