### ISSUE TITLE
same provider not working for injected and other wallets

### ISSUE THREAD

**Issue by khushnood1037** [blocknative/web3-onboard#1912] opened 2023-09-19 05:28 UTC
### Current Behavior

Is there a way to get an event about the type of wallet that user has connected to i.e, whether the wallet is injected one or not?

### Expected Behavior

Need to work same provider for injected wallets and other wallets as well.

### Steps To Reproduce

Can you please let us know how to reuse same provider for injected wallets and other ones.
 Like I am using the following structure in my Application:-
 -Firstly I've a connectWallet file  where I've initialized wallet connectivity.
 -second file is where I've instance setup. 
 -third one is where I've defined send METHODS
 Now whenever I'll make any transaction using the same provider that I had initalized while invoking the Onboard.connect() method,it is working fine with injected wallets but facing issue with wallet connect(not injected).

### What package is effected by this issue?

@web3-onboard/core

### Is this a build or a runtime issue?

Runtime

### Package Version

"^2.8.11",

### Node Version

v18.17.1

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
send method does not exist on provider
```

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by taylorjdawson** [comment] 2023-09-21 17:21
Hey @khushnood1037 👋 So I think the issue is in that you are trying to use the [deprecated send](https://eips.ethereum.org/EIPS/eip-1193#send-deprecated) method. Web3onboard returns an [EIP-1193 compliant provider](https://eips.ethereum.org/EIPS/eip-1193), therefore when calling methods on the provider make sure it conforms to that standard. In this case you want to use the [`window.ethereum.request`](https://eips.ethereum.org/EIPS/eip-1193#request) method. Let me know if that helps!

**Comment by Adamj1232** [comment] 2023-10-02 17:54
@khushnood1037 friendly ping to see if the above comment helped resolve your problem 😄

**Comment by Adamj1232** [comment] 2023-10-11 15:53
@khushnood1037 wanted to check with you one last time before closing this issue if this is still causing problems on your end 😄

**Comment by Adamj1232** [comment] 2023-10-17 23:12
@khushnood1037 we are going to close this for now as it has become stale and has a proposed fix above. Please feel free to continue the conversation should the issue persist. Thanks!

**Closed by Adamj1232** 2023-10-17 23:12 UTC
Labels: bug
