### ISSUE TITLE
with-vanilla-js example doesn't work because it has missing file

### ISSUE THREAD

**Issue by nickgreen5** [blocknative/web3-onboard#1664] opened 2023-04-27 09:34 UTC
There is no bundle.js file and this file is included inside index.html. This is why the example doesn't work.

I did exact steps as mentioned in readme:
```
Clone this repo

https://github.com/blocknative/web3-onboard.git
Navigate to the project directory:

cd examples/with-vanilla-js
Install the dependencies:

npm install
Run the development server:

npm run dev
```
Still there is no bundle.js file that is included in index.html
`<script defer src="dist/bundle.js"></script>
`

**Comment by leightkt** [comment] 2023-04-27 09:48
@nickgreen5 the bundle.js file is not missing- it is automatically generated by webpack upon running `npm run dev` or` npm run build`. 
I am able to run successfully locally from the folder examples/with-vanilla-js by running `npm install && npm run dev`
Are you sure you're running the commands from within the `with-vanilla-js` folder?

**Comment by nickgreen5** [comment] 2023-04-27 16:44
Step run npm run build is not mentioned in the readme. I run now also this and it created folder dist (which hasn't been created by running only npm run dev), however there is still no bundle.js file inside, it created bunch of other files. Maybe it has something to do with Windows?

**Comment by nickgreen5** [comment] 2023-04-28 08:46
@leightkt it is not required to run the dev server but it is required to run the examples because the example has included bundle.js file inside index.html.

I just checked webpack.config.js file, I am not sure how it supposed to create bundle.js file if this name is not mentioned anywhere:
```
const path = require('path')

module.exports = {
  entry: './src/index.js',
  output: {
    filename: '[name].js',
    path: path.resolve(__dirname, 'dist'),
    clean: true
  },
  module: {
    rules: [
      {
        test: /\.css$/,
        use: ['style-loader', 'css-loader']
      },
      {
        test: /\.m?js/,
        resolve: {
          fullySpecified: false
        }
      }
    ]
  },
  devServer: {
    historyApiFallback: true,
    static: { directory: path.join(__dirname, '/') },
    port: 9000
  },
  optimization: {
    runtimeChunk: 'single'
  }
}

```

![files](https://user-images.githubusercontent.com/128820398/235100810-27e8fd97-b4e3-4413-a5a8-9afc957669ea.png)
![devrun](https://user-images.githubusercontent.com/128820398/235100816-7431f1c3-e089-4836-9fae-e1c37f2abde8.png)

**Comment by leightkt** [comment] 2023-04-28 09:03
@nickgreen5 it's created by webpack for you under the hood when you run `npm run dev`. 

Please make sure you have webpack installed- [https://webpack.js.org/guides/installation/](https://webpack.js.org/guides/installation/)
Here is the [webpack documentation](https://webpack.js.org/) for your reference.

**Comment by nickgreen5** [comment] 2023-04-28 20:39
@leightkt sorry to be little annoying but I just tried the same thing on Ubuntu machine, followed the exact steps and again there is no bundle.js file. Also asked my friend and the same. There must be missing some step in instructions I guess for those who newly installed npm and webpack, I don't see any other explanation why following the exact steps on 3 different machines, including Ubuntu, didn't create bundle.js file.

**Comment by leightkt** [comment] 2023-05-01 15:04
@nickgreen5 it's because webpack is serving bundle.js from memory when you run the dev server, so it's not something you're going to see listed in the files structure. It's there- behind the scenes.

**Comment by Mallinanga** [comment] 2023-05-04 06:32
Ditto... Same happens for me too. 404 on the dist/bundle.js
Maybe it has something to do with the webpack-dev-server version?

**Comment by leightkt** [comment] 2023-05-04 18:29
@Mallinanga Ok- thanks for the report- reopening re-examining!

**Comment by Mallinanga** [comment] 2023-05-04 19:34
I managed to make it work by adding:

`
<script src="/runtime.js"></script>
 <script src="/main.js"></script>
`

instead of the provided /dist/bundle.js

**Comment by nickgreen5** [comment] 2023-05-06 13:30
@leightkt  npm i -D webpack-dev-server seems to resolved missing bundle.js

> I managed to make it work by adding:
> 
> ```
> <script src="/runtime.js"></script>
> <script src="/main.js"></script>
> ```
> 
> instead of the provided /dist/bundle.js

Thx, that almost resolved my problem too. I needed to add also defer attribute to script tag. However now I get different error if I click WalletConnect button. Does it work for you? I get this error:
99.js:1 Uncaught (in promise) ReferenceError: Buffer is not defined
    at t.exports (2199.js:1:82278)
    at g (2199.js:1:7507)
    at Module.ot (2199.js:1:31294)
    at lt._generateKey (2199.js:1:29246)
    at lt.createSession (2199.js:1:19338)
    at l.code (main.js:2:399437)
    at new Promise (<anonymous>)
    at provider.chains.request (main.js:2:398907)
    at Oa (main.js:2:594847)
    at R (main.js:2:659537)
t

**Comment by nickgreen5** [comment] 2023-05-06 13:37
> @Mallinanga I was able to solve by running `npm i -D webpack-dev-server`- I think I accidentally left webpack-dev-server off the dependencies. Let me know if that helps solve without needing to change the src.

@leightkt that finally resolved bundle.js problem on my side. I really appreciate your help, however I thought the purpose of vanilla js example was that you don't need nodejs to run the script but you could simply include files into html which is not in this case.

**Comment by nickgreen5** [comment] 2023-05-06 14:11
> @Mallinanga I was able to solve by running `npm i -D webpack-dev-server`- I think I accidentally left webpack-dev-server off the dependencies. Let me know if that helps solve without needing to change the src.

@leightkt I appreciate all your help. However this didn't solve the problem on my side, still getting the same error. I thought that the purpose of vanilla js example was that you could simply include js files into html and run the example without running npm/nodejs.

**Comment by leightkt** [comment] 2023-05-08 17:01
@nickgreen5 you'll need a module bundler- like webpack- to use the web3onboard package. It has a lot of complex dependencies and uses "bare" imports not supported in browser.

**Comment by leightkt** [comment] 2023-05-08 21:28
@nickgreen5 I was able to reproduce the walletConnect error- I'll push some updates to the example

**Comment by leightkt** [comment] 2023-05-10 17:00
@nickgreen5 I pushed some changes to the vanilla-js demo: 
https://github.com/blocknative/web3-onboard/tree/develop/examples/with-vanilla-js

Let me know if this gets you up and running!

**Comment by Adamj1232** [comment] 2023-05-11 15:45
Merged in latest release! Feel free to continue the conversation here if an issue arises.

**Closed by Adamj1232** 2023-05-11 15:45 UTC

**Comment by nickgreen5** [comment] 2023-06-05 11:59
Just wanted to write follow update for those who want to run this like really old school way pure js without nodejs. Do all the mentioned steps, then run `npm run build` and then just copy all files to localhost, then change 
```
    <script defer src="/runtime.js"></script>
    <script defer src="/main.js"></script>
```
into    
```
    <script defer src="dist/runtime.js"></script>
    <script defer src="dist/main.js"></script>
```
This did trick to me, now I can simply just copy all files to my php project.
