### ISSUE TITLE
[Bug]: WalletCheck network change resets to chainId 1

### ISSUE THREAD

**Issue by itsmnthn** [blocknative/web3-onboard#764] opened 2021-12-20 04:54 UTC
### Current Behavior

Happens with MetaMask:
When using `walletCheck()` to check the selected network is correct or not (here correct network is Avalanche Fuji Testnet) and using `subscriptions.network` to listen network changes
1. On correct network connect MetaMask using `walletSelect()`
2. Change the network on MetaMask
3. Use the `walletCheck()` to prompt switch network on MetaMask
4. Deny the switch network request on MetaMask
5. Use the `walletCheck()` again to prompt switch network on MetaMask
6. Accept the switch network request on MetaMask

on 6th step onboard doesn't update the network it resets to chainId 1 (mainnet - Ethereum) and `walletCheck()` prompts ask to switch to correct network but the MetaMask has correct network selected

### Expected Behavior

Happens with MetaMask:
When using `walletCheck()` to check the selected network is correct or not (here correct network is Avalanche Fuji Testnet) and using `subscriptions.network` to listen network changes
1. On correct network connect MetaMask using `walletSelect()`
2. Change the network on MetaMask
3. Use the `walletCheck()` to prompt switch network on MetaMask
4. Deny the switch network request on MetaMask
5. Use the `walletCheck()` again to prompt switch network on MetaMask
6. Accept the switch network request on MetaMask

on 6th step onboard should update the network instead resets to chainId 1 (mainnet - Ethereum) and `walletCheck()` prompts should close

### Steps To Reproduce

Steps are mentioned in Current Behavior

### Onboard Version

^1.35.4

### Node Version

14.17.6

### What browsers are you seeing the problem on?

Microsoft Edge

**Comment by jpangelle** [comment] 2022-02-06 22:52
getting the same issue

**Comment by taylorjdawson** [comment] 2022-02-06 23:04
@jpangelle @itsmnthn I am not seeing this on v`1.37.3`. I included a video of the steps, let me know if I am doing them correctly 

https://user-images.githubusercontent.com/29665732/152705282-1dba305b-126e-4545-8266-d39df5b6a74d.mp4

**Comment by jpangelle** [comment] 2022-02-07 04:03
I am using the `network` subscription callback and I am logging out the argument being passed in:

```ts
const onboard = Onboard({
  dappId: BLOCKNATIVE_KEY,
  networkId: NETWORK_ID,
  subscriptions: {
    network: network => {
      console.log(network);
      // logs out "1" (mainnet) and then quickly switches to the correct network in Metamask
    },
    wallet: wallet => {
      // instantiate web3 when the user has selected a wallet
      web3 = new Web3(wallet.provider);
      console.log(`${wallet.name} connected!`);
    },
  },
});
```

**Comment by jpangelle** [comment] 2022-02-07 04:29
The `networkId` variable has a quick lifecycle of `null` -> `1` -> my correct network:
https://github.com/blocknative/onboard/blob/develop/src/onboard.ts#L164-L170

**Comment by taylorjdawson** [comment] 2022-02-25 00:18
@jpangelle @itsmnthn 
Could one of you provide a video showing the issue? I still am unable to repro. The video includes the console logging the network

https://user-images.githubusercontent.com/29665732/155629503-a107928e-ea59-4f9d-a9af-dce7af91e607.mp4

**Comment by Adamj1232** [comment] 2022-06-28 20:42
Closing as this issue has been unable to reproduce. If this is still an issue please comment and reopen. Thank you again!

**Closed by Adamj1232** 2022-06-28 20:42 UTC
Labels: bug, v1-onboard
