### ISSUE TITLE
[Bug]: unknown address when logging in with hardware wallet and choosing custom path

### ISSUE THREAD

**Issue by JackHamer09** [blocknative/web3-onboard#828] opened 2022-02-15 16:24 UTC
### Current Behavior

When not filling in the custom derivation path and choosing it you will be logged in with some address that you can't find in your Trezor accounts. You won't be offered to choose from the list of accounts

### Expected Behavior

When not filling in the custom derivation path and choosing it you will see an error asking you to provide a correct derivation path
**OR**
Use the default Ethereum derivation path when the custom derivation path is empty

### Steps To Reproduce

1. Onboard window shows up
2. You select a hardware wallet (Trezor for example)
3. You see a window offering to choose Ethereum derivation path or custom derivation path
4. Click on custom derivation path but don't fill the field, leave it empty
5. Click connect
6. You will be logged in with some address that you can't find in your Trezor accounts. You won't be offered to choose from the list of accounts

### Onboard Version

1.34.2

### Node Version

14.17.4

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

**Comment by taylorjdawson** [comment] 2022-02-25 16:46
@JackHamer09 Thanks for bringing this to our attention we will take a look!

**Comment by bxpana** [comment] 2022-04-07 17:42
@taylorjdawson Has any progress been made on this issue?

**Comment by Adamj1232** [comment] 2022-06-28 20:45
@JackHamer09  @bxpana is this still an issue you are experiencing?

**Comment by Adamj1232** [comment] 2022-07-05 18:03
Closing as I am unable to reproduce with the latest versions of the onboard packages (HD/core/react). If this issue persists please feel free to re-open the issue. Thank you again for using Blocknative!

**Closed by Adamj1232** 2022-07-05 18:03 UTC
Labels: bug, v1-onboard
