### ISSUE TITLE
[Bug] Wallet Connect + Zengo

### ISSUE THREAD

**Issue by SpiritusDeos** [blocknative/web3-onboard#1650] opened 2023-04-19 06:19 UTC
### Current Behavior

Using the v2 of wallet connect with the correct configured chain, but Zengo wallet return "QR code invalid".

### Expected Behavior

Zengo to connect to wallet connect

### Steps To Reproduce

1. Instantiate a v2 instance of wallet connect
2. Open Zengo and scan wallet connect QR code
3. Zengo returns "Invalid QR code"

Here the code to instantiate wallet connect v2

```
const wcV2InitOptions = {
    version: 2,
    requiredChains: NUXT_ENVIRONMENT === 'production' ? [1, 137] : [8001, 5],
    projectId: WALLET_CONNECT_ID
};
```

### What package is effected by this issue?

@web3-onboard/core

### Is this a build or a runtime issue?

Runtime

### Package Version

2.6.2

### Node Version

16.13

### Relevant log output

```shell
"QR code invalid"
```

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by Adamj1232** [comment] 2023-04-19 14:55
@kennyyS please open an issue with the WalletConnect or ZenGo teams as we don't control interactions between wallets and walletConnect. Also please note that not all wallets have updated to use walletConnect V2 (including MetaMask). Closing as this issue is between WalletConnect and ZenGo

**Comment by kennyyS** [comment] 2023-04-19 15:51
@Adamj1232 I made it work using WalletConnect V2 SDK with Zengo two hours ago... 

Are you sure it's not a web3-onboad related issue ?

**Comment by Adamj1232** [comment] 2023-04-19 15:55
@kennyyS are other wallets working with WalletConnect and web3-onboard?
If you can provide a reproducible example that would be very helpful

**Comment by Adamj1232** [comment] 2023-04-19 15:59
The walletConnect team developed out the web3-onboard module and it doesn't use the SDK but rather a couple sub-libraries. It may be that some of those libraries are not up to date currently.

**Comment by kennyyS** [comment] 2023-04-19 16:12
I will try to bring you a complete example asap, but basically a basic setup of web3-onboard with the wallet connect extension and this pat of the code is enough, to see the error:

```
const wcV2InitOptions = {
    version: 2,
    requiredChains:  [1, 137],
    projectId: WALLET_CONNECT_ID
};
```

**Comment by Adamj1232** [comment] 2023-04-19 16:13
@kennyyS can you please test this flow with this link when you have a moment? - https://staging.reactdemo.blocknative.com/

**Comment by kennyyS** [comment] 2023-04-19 16:14
Get the same issue - "Invalid QR code" - it's working with the native SDK that's why I am thinking about an existing issue with web3 onboard

**Comment by kennyyS** [comment] 2023-04-19 16:21
By the way @Adamj1232 it's working well with wallet connect v1 - as I am using it in production

**Comment by Adamj1232** [comment] 2023-04-19 16:25
Reopening the issue and raising with the WalletConnect team - cc @ganchoradkov

**Comment by Adamj1232** [comment] 2023-04-19 16:29
@kennyyS I suspect a misalignment in walletconnect packages between what the sdk uses and what is used within web3-onboard especially since it is working with V1. I have raised with the WC team and will follow up here as we get info

**Comment by kennyyS** [comment] 2023-04-23 16:13
👋🏻 , any news about this ?

**Comment by Adamj1232** [comment] 2023-04-28 17:05
Hi @SpiritusDeos ! We are still working through this issue with the WC team and will update here as progress is made

**Closed** 2023-05-01 14:51 UTC
Labels: bug
